version: '3.8'

services:
  metodos-numericos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metodos-numericos-app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
