[theme]
primaryColor = "#367C2B"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#2c3e50"
font = "sans serif"
base = "light"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "info"
